name: Autograding Tests
on:
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]' && github.actor != 'jacobsteffenBYU'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12.6
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install pytest pytest-subtests 'black<=22.3.0' 'tomli>=1.1.0' 'timeout-decorator~=0.5.0'
    - name: tests/test_01_input_prompts.py
      id: tests-test-01-input-prompts-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-01-input-prompts
        setup-command: ''
        command: python -m pytest -v tests/test_01_input_prompts.py
        timeout: 30
        max-score: 10
    - name: tests/test_02_printed_messages.py
      id: tests-test-02-printed-messages-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-02-printed-messages
        setup-command: ''
        command: python -m pytest -v tests/test_02_printed_messages.py
        timeout: 30
        max-score: 10
    - name: tests/test_03_no_tie_scores.py
      id: tests-test-03-no-tie-scores-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-03-no-tie-scores
        setup-command: ''
        command: python -m pytest -v tests/test_03_no_tie_scores.py
        timeout: 30
        max-score: 25
    - name: tests/test_04_correct_range_random_scores.py
      id: tests-test-04-correct-range-random-scores-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-04-correct-range-random-scores
        setup-command: ''
        command: python -m pytest -v tests/test_04_correct_range_random_scores.py
        timeout: 30
        max-score: 15
    - name: tests/test_05_storing_win_and_loss_teams.py
      id: tests-test-05-storing-win-and-loss-teams-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-05-storing-win-and-loss-teams
        setup-command: ''
        command: python -m pytest -v tests/test_05_storing_win_and_loss_teams.py
        timeout: 30
        max-score: 25
    - name: tests/test_06_final_performance_messages.py
      id: tests-test-06-final-performance-messages-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-06-final-performance-messages
        setup-command: ''
        command: python -m pytest -v tests/test_06_final_performance_messages.py
        timeout: 30
        max-score: 10
    - name: tests/test_07_sufficient_comments.py
      id: tests-test-07-sufficient-comments-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-07-sufficient-comments
        setup-command: ''
        command: python -m pytest -v tests/test_07_sufficient_comments.py
        timeout: 30
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTS-TEST-01-INPUT-PROMPTS-PY_RESULTS: ${{steps.tests-test-01-input-prompts-py.outputs.result}}
        TESTS-TEST-02-PRINTED-MESSAGES-PY_RESULTS: ${{steps.tests-test-02-printed-messages-py.outputs.result}}
        TESTS-TEST-03-NO-TIE-SCORES-PY_RESULTS: ${{steps.tests-test-03-no-tie-scores-py.outputs.result}}
        TESTS-TEST-04-CORRECT-RANGE-RANDOM-SCORES-PY_RESULTS: ${{steps.tests-test-04-correct-range-random-scores-py.outputs.result}}
        TESTS-TEST-05-STORING-WIN-AND-LOSS-TEAMS-PY_RESULTS: ${{steps.tests-test-05-storing-win-and-loss-teams-py.outputs.result}}
        TESTS-TEST-06-FINAL-PERFORMANCE-MESSAGES-PY_RESULTS: ${{steps.tests-test-06-final-performance-messages-py.outputs.result}}
        TESTS-TEST-07-SUFFICIENT-COMMENTS-PY_RESULTS: ${{steps.tests-test-07-sufficient-comments-py.outputs.result}}
      with:
        runners: tests-test-01-input-prompts-py,tests-test-02-printed-messages-py,tests-test-03-no-tie-scores-py,tests-test-04-correct-range-random-scores-py,tests-test-05-storing-win-and-loss-teams-py,tests-test-06-final-performance-messages-py,tests-test-07-sufficient-comments-py
