name: Autograding Tests
on:
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]' && github.actor != 'jacobsteffenBYU'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12.6
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install pandas openpyxl pytest pytest-subtests 'black<=22.3.0' 'tomli>=1.1.0' 'timeout-decorator~=0.5.0'
    - name: tests/test_1_input_prompts.py
      id: tests-test-1-input-prompts-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-1-input-prompts
        setup-command: ''
        command: python -m pytest -v tests/test_1_input_prompts.py
        timeout: 30
        max-score: 10
    - name: tests/test_2_printed_messages.py
      id: tests-test-2-printed-messages-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-2-printed-messages
        setup-command: ''
        command: python -m pytest -v tests/test_2_printed_messages.py
        timeout: 30
        max-score: 10
    - name: tests/test_3_no_tie_scores.py
      id: tests-test-3-no-tie-scores-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-3-no-tie-scores
        setup-command: ''
        command: python -m pytest -v tests/test_3_no_tie_scores.py
        timeout: 30
        max-score: 25
    - name: tests/test_4_correct_range_random_scores.py
      id: tests-test-4-correct-range-random-scores-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-4-correct-range-random-scores
        setup-command: ''
        command: python -m pytest -v tests/test_4_correct_range_random_scores.py
        timeout: 30
        max-score: 15
    - name: tests/test_5_storing_win_and_loss_teams.py
      id: tests-test-5-storing-win-and-loss-teams-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-5-storing-win-and-loss-teams
        setup-command: ''
        command: python -m pytest -v tests/test_5_storing_win_and_loss_teams.py
        timeout: 30
        max-score: 25
    - name: tests/test_6_final_performance_messages.py
      id: tests-test-6-final-performance-messages-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-6-final-performance-messages
        setup-command: ''
        command: python -m pytest -v tests/test_6_final_performance_messages.py
        timeout: 30
        max-score: 10
    - name: tests/test_7_sufficient_comments.py
      id: tests-test-7-sufficient-comments-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-7-sufficient-comments
        setup-command: ''
        command: python -m pytest -v tests/test_7_sufficient_comments.py
        timeout: 30
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTS-TEST-1-INPUT-PROMPTS-PY_RESULTS: ${{steps.tests-test-1-input-prompts-py.outputs.result}}
        TESTS-TEST-2-PRINTED-MESSAGES-PY_RESULTS: ${{steps.tests-test-2-printed-messages-py.outputs.result}}
        TESTS-TEST-3-NO-TIE-SCORES-PY_RESULTS: ${{steps.tests-test-3-no-tie-scores-py.outputs.result}}
        TESTS-TEST-4-CORRECT-RANGE-RANDOM-SCORES-PY_RESULTS: ${{steps.tests-test-4-correct-range-random-scores-py.outputs.result}}
        TESTS-TEST-5-STORING-WIN-AND-LOSS-TEAMS-PY_RESULTS: ${{steps.tests-test-5-storing-win-and-loss-teams-py.outputs.result}}
        TESTS-TEST-6-FINAL-PERFORMANCE-MESSAGES-PY_RESULTS: ${{steps.tests-test-6-final-performance-messages-py.outputs.result}}
        TESTS-TEST-7-SUFFICIENT-COMMENTS-PY_RESULTS: ${{steps.tests-test-7-sufficient-comments-py.outputs.result}}
      with:
        runners: tests-test-1-input-prompts-py,tests-test-2-printed-messages-py,tests-test-3-no-tie-scores-py,tests-test-4-correct-range-random-scores-py,tests-test-5-storing-win-and-loss-teams-py,tests-test-6-final-performance-messages-py,tests-test-7-sufficient-comments-py
